name: ShellCheck

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - master

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt update && sudo apt install shellcheck -y

      - name: Run ShellCheck
        run: |
          shellcheck *.sh
          if [ $? -ne 0 ]; then
            echo "ShellCheck Detected Errors!!!"
            exit 1
          fi

      - name: Install shfmt
        run: |
          curl -sfL https://install.goreleaser.com/github.com/mvdan/sh/releases/latest/download/shfmt_linux_amd64.tar.gz | tar xvz
          sudo mv shfmt /usr/local/bin/

      - name: Format Shell Scripts
        run: |
          find . -name "*.sh" -exec shfmt -w -i 2 {} \;
